name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build-java:
   
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout files    
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.MY_ACCESS_TOKEN }}
          password: ${{ secrets.MY_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/footballvotingdemo/app:latest
        
  deploy:
    needs: build-java
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout files    
        uses: actions/checkout@v4
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.MY_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: |
          doctl registry login
         
      - name: Docker Pull and Run on Droplet
        run: |
          docker pull registry.digitalocean.com/footballvotingdemo/app:latest
          docker run -d -p 80:80 registry.digitalocean.com/footballvotingdemo/app:latest


    
